services:
  everlink:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: DEBUG
      # LOG_FILE:
      CUSTOM_SERVICES_PATH: "/custom-services"
    volumes:
      - ./custom-services:/custom-services